// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pewzzvstteotowipssbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBld3p6dnN0dGVvdG93aXBzc2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzI1MDYsImV4cCI6MjA3MTEwODUwNn0.QOhC5w4DBOCAKKwIPUdRtX-r6LiAse7S6SQZ3BIanzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});